name: auto PR
on:
  push:
    branches: ["prepod"]

jobs:
  pull-request:
    name: open auto PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "master"
          pr_title: "Pulling ${{ github.ref }} into main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
